//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnglishForKids_LMN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public int ID_Question { get; set; }
        public string Content { get; set; }
        public string Type_Question { get; set; }
        public string Answer_Content1 { get; set; }
        public string Answer_Content2 { get; set; }
        public string Answer_Content3 { get; set; }
        public string Answer_Content4 { get; set; }
        public string Answer_Correct { get; set; }
        public Nullable<int> ID_Test { get; set; }
    
        public virtual Test Test { get; set; }
    }
}
