//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnglishForKids_LMN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quiz_Details
    {
        public Nullable<double> Quiz_Score { get; set; }
        public string Time_Quiz { get; set; }
        public int ID_Category_Vo { get; set; }
        public int ID_User { get; set; }
        public int ID_Quiz { get; set; }
    
        public virtual Category_Vo Category_Vo { get; set; }
        public virtual Quiz Quiz { get; set; }
        public virtual User User { get; set; }
    }
}
