//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnglishForKids_LMN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Story
    {
        public int ID_Story { get; set; }
        public string Name_Story { get; set; }
        public string EN_Content { get; set; }
        public string VN_Content { get; set; }
        public string Image_Story { get; set; }
        public string Audio { get; set; }
        public Nullable<int> View_Story { get; set; }
        public string Banner { get; set; }
        public Nullable<int> ID_Category { get; set; }
        public Nullable<int> ID_User { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual User User { get; set; }
    }
}
