//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnglishForKids_LMN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test_Details
    {
        public Nullable<double> Test_Score { get; set; }
        public string Time_Test { get; set; }
        public int ID_User { get; set; }
        public int ID_Test { get; set; }
    
        public virtual Test Test { get; set; }
        public virtual User User { get; set; }
    }
}
